---
spring:
    application:
        name: CF-WORKSHOP-SPRING-BOOT
    jpa:
        hibernate:
            ddl-auto: create
security:
    basic:
        enabled: false
logging:
    level:
        org:
            springframework:
                web: INFO
        io:
            pivotal: DEBUG
        com:
            netflix:
                discovery: DEBUG
management:
    endpoints:
        enabled-by-default: true
    info:
        git:
            mode: full